name: Website Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # This will run every 5 minutes
  workflow_dispatch:

jobs:
  monitor_websites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check kuapa.com for text
        id: kuapa_check
        run: |
          # Use curl to get the HTML content and check for the string
          # grep -q returns exit code 0 if the pattern is found, 1 if not.
          if curl -s 'https://kuapa.com' | grep -q 'กั่วป่า ( Kuapa)'; then
            echo "Kuapa.com is healthy."
          else
            echo "Kuapa.com is down."
            exit 1
          fi
      
      - name: Send LINE alert for kuapa.com failure
        if: failure() && steps.kuapa_check.conclusion == 'failure'
        run: |
          MESSAGE='{"to":"${{ secrets.LINE_USER_ID }}","messages":[{"type":"text","text":"Alert: น้องบาว..แลถา kuapa.com มีปัญหาเด้"}]}'
          curl -X POST https://api.line.me/v2/bot/message/push \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}' \
            -d "$MESSAGE"
      
      - name: Check weddingmc.in.th for text
        id: weddingmc_check
        run: |
          if curl -s 'https://weddingmc.in.th/about-2/' | grep -q 'อัญชุลี โสภารัตน์'; then
            echo "Weddingmc is healthy."
          else
            echo "Weddingmc is down."
            exit 1
          fi
          
      - name: Send LINE alert for weddingmc.in.th failure
        if: failure() && steps.weddingmc_check.conclusion == 'failure'
        run: |
          MESSAGE='{"to":"${{ secrets.LINE_USER_ID }}","messages":[{"type":"text","text":"Alert: น้องบาว...ไม่โร่ weddingmc.in.th เป็นไหร่หลาว ไปแลทีต๊ะ"}]}'
          curl -X POST https://api.line.me/v2/bot/message/push \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}' \
            -d "$MESSAGE"
