name: Test Cron Schedule

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  test-cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job ran successfully!"
